# Generated by Django 4.2.7 on 2023-12-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_1_autoresponder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='user_2_autoresponder',
            field=models.BooleanField(default=False),
        ),
    ]
